redis:
    image: redis:3.0
    ports:
        - "6379:6379"
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        - ./data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf

base:
    build: base

elasticsearch:
    build: elasticsearch
    environment:
        - ELASTICSEARCH_PLUGINS
    volumes_from:
        - dataelasticsearch

dataelasticsearch:
    image: busybox
    volumes:
        - /usr/share/elasticsearch/data

logstash:
    build: logstash
    environment:
        - REDIS_PASSWORD
    links:
        - redis
        - elasticsearch

kibana:
    build: kibana
    ports:
        - "80:80"
    environment:
        - KIBANA_HTACCESS
    links:
        - elasticsearch
