redis:
    image: redis:3.0
    ports:
        - "6379:6379"
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        - ./data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf

elasticsearch:
    build: elasticsearch
    volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data
    command: elasticsearch
        -Des.node.name="Grumpy Cat"
        -Des.cluster.name="kibana"
        -Des.index.number_of_replicas=0

logstash:
    image: logstash:2.1
    volumes:
        - ./logstash.conf:/usr/local/etc/logstash/logstash.conf
    links:
        - redis
        - elasticsearch
    command: logstash
        -f /usr/local/etc/logstash/logstash.conf

kibana:
    build: kibana
    ports:
        - "80:80"
    links:
        - elasticsearch
